version: 3

images:
  base_image:
    name: quay.io/ansible/creator-base:latest

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  ansible_core:
    package_pip: ansible-core>=2.14
  ansible_runner:
    package_pip: ansible-runner

additional_build_files:
  - src: files/netrc
    dest: netrc

additional_build_steps:
  append_base:
    - COPY _build/netrc/netrc /root/.netrc
    - RUN chmod 600 /root/.netrc
    - RUN mkdir -p /home/runner && cp /root/.netrc /home/runner/.netrc && chown 1000:0 /home/runner/.netrc && chmod 600 /home/runner/.netrc
